;;;; This file was generated by
;;;;
;;;;   (autoload:record-system-autoloads "%autoload-test")
;;;;
;;;; Do not edit.

(common-lisp:in-package :%autoload-test)

(autoload foo "%autoload-test/full" :arglist '(x) :docstring "foo docstring")

(defvar/autoload *var/no-value* :docstring "*var/no-value* docstring")

(defvar/autoload *var/simple-value* :initial-value '("xxx" 7 :key nil t)
                 :docstring "*var/simple-value* docstring")

(defvar/autoload *var/complex-value*)
