;;;; This file was generated by
;;;;
;;;;   (autoload:record-system-autoloads "%package-test")
;;;;
;;;; Do not edit.

(in-package :cl)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (autoload::ensure-package-names "%package-test" '("%ptest" "%ptest-alt"))
  (setf (documentation (find-package (autoload::native-name "%package-test"))
                       t)
          "%PACKAGE-TEST docstring")
  (autoload::ensure-package-names "%aaa" nil)
  (autoload::shadow* '("cons" "ghost-shadow") "%package-test")
  (autoload::shadowing-import/existing '(("%3rd-party" . "shadow-target"))
                                       "%package-test")
  (autoload::use-package/existing '("common-lisp" "autoload" "%aaa")
                                  "%package-test")
  (autoload::use-package/existing '("common-lisp" "%package-test") "%aaa")
  (autoload::import/existing '(("%3rd-party" . "plain-import-target"))
                             "%package-test")
  (autoload::import/existing '(("%3rd-party" . "missing")) "%aaa")
  (autoload::intern-and-export '("plain-import-target" "foo") "%package-test")
  (autoload::intern-and-export '("missing" "aaa-foo") "%aaa"))
