;;;; This file was generated by
;;;;
;;;;   (autoload:record-loaddefs "%package-test")
;;;;
;;;; Do not edit.

(in-package :cl)

(autoload::ensure-package-names "%aaa" nil)

(autoload::ensure-package-names "%package-test" '("%ptest" "%ptest-alt"))

(autoload::set-package-documentation "%package-test"
                                     "%PACKAGE-TEST docstring")

(autoload::shadow* '("cons" "ghost-shadow") "%package-test")

(autoload::shadowing-import* '(("%3rd-party" . "shadow-target"))
                             "%package-test")

(autoload::use-package* '("%package-test" "common-lisp") "%aaa")

(autoload::use-package* '("%aaa" "autoload" "common-lisp") "%package-test")

(autoload::import* '(("%3rd-party" . "missing")) "%aaa")

(autoload::import*
 '(("%3rd-party" . "plain-import-target") ("%aaa" . "forward-import-target")
   ("%aaa" . "forward-import-target"))
 "%package-test")

(autoload::export* '("aaa-foo" "forward-import-target" "missing") "%aaa")

(autoload::export* '("foo" "plain-import-target") "%package-test")
