;;;; This file was generated by
;;;;
;;;;   (autoload:record-loaddefs "%simple-test")
;;;;
;;;; Do not edit.

(in-package :cl)

(autoload::foreshadow-defvar %simple-test::*var/circular-value*)

(autoload::foreshadow-defvar %simple-test::*var/complex-value*)

(autoload::foreshadow-defvar %simple-test::*var/no-value* :docstring
                             "*var/no-value* docstring")

(autoload::foreshadow-defvar %simple-test::*var/simple-value* :init
                             '("xxx" 7 :key nil t) :docstring
                             "*var/simple-value* docstring")

(autoload:autoload %simple-test::foo "%simple-test/full" :arglist
                   "(%simple-test::x)" :docstring "foo docstring")

(autoload:autoload %simple-test::foo-gf "%simple-test/full" :arglist
                   "(%simple-test::x)" :docstring "foo-gf docstring")

(autoload:autoload %simple-test::foo-with-unreadable-arglist
                   "%simple-test/full" :arglist
                   "(&optional (%simple-test::x '%3rd-party::z))")

(autoload:autoload %simple-test::test-custom-fun "%simple-test/full" :arglist
                   "(%simple-test::x)")

(autoload:autoload (setf %simple-test::xxx) "%simple-test/full" :arglist
                   "(%simple-test::x)")

(autoload:autoload-class %simple-test::test-custom-class "%simple-test/full")
