;;;; This file was generated by
;;;;
;;;;   (autoload:record-system-autoloads "%simple-test")
;;;;
;;;; Do not edit.

(in-package :cl)

(autoload:autoload %simple-test::foo "%simple-test/full" :arglist
                   "(%simple-test::x)" :docstring "foo docstring")

(autoload:defvar/autoload %simple-test::*var/no-value* :docstring
                          "*var/no-value* docstring")

(autoload:defvar/autoload %simple-test::*var/simple-value* :init
                          '("xxx" 7 :key nil t) :docstring
                          "*var/simple-value* docstring")

(autoload:defvar/autoload %simple-test::*var/complex-value*)

(autoload:autoload %simple-test::foo-with-unreadable-arglist
                   "%simple-test/full" :arglist
                   "(&optional (%simple-test::x (quote %3rd-party::z)))")
